# Generated by Django 4.0.2 on 2022-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200, unique=True)),
                ('ebitdaMargins', models.FloatField(blank=True, default=0, null=True)),
                ('sector', models.CharField(blank=True, max_length=200)),
                ('yearReturn', models.FloatField(blank=True, null=True)),
                ('pegRatio', models.FloatField(blank=True, default=0, null=True)),
                ('shortPercentOfFloat', models.FloatField(blank=True, default=0, null=True)),
                ('marketCap', models.FloatField(blank=True, default=0, null=True)),
                ('payoutRatio', models.FloatField(blank=True, null=True)),
                ('fullTimeEmployees', models.FloatField(blank=True, null=True)),
                ('teps', models.FloatField(blank=True, default=0, null=True)),
                ('feps', models.FloatField(blank=True, default=0, null=True)),
                ('fpe', models.FloatField(blank=True, default=0, null=True)),
                ('ptb', models.FloatField(blank=True, default=0, null=True)),
                ('roe', models.FloatField(blank=True, default=0, null=True)),
                ('currentRatio', models.FloatField(blank=True, default=0, null=True)),
                ('debtEquityRatio', models.FloatField(blank=True, default=0, null=True)),
                ('insiders', models.FloatField(default=0)),
                ('tcps', models.FloatField(default=0)),
                ('quickRatio', models.FloatField(blank=True, default=0, null=True)),
                ('shortName', models.CharField(blank=True, default='', max_length=222)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('sharesPercentSharesOut', models.FloatField(default=0)),
            ],
        ),
    ]
