# Generated by Django 4.0.2 on 2022-02-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topTen', '0002_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='normalize',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
