# Generated by Django 4.0.2 on 2022-03-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topTen', '0004_options_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fullTimeEmployees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
