# Generated by Django 4.0.2 on 2022-03-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topTen', '0005_alter_stock_fulltimeemployees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='marketCap',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
