# Generated by Django 4.0.2 on 2022-03-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topTen', '0006_alter_stock_marketcap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectoroptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortBy', models.CharField(blank=True, max_length=200)),
                ('normalize', models.BooleanField(blank=True, default=False)),
                ('dir', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
