# Generated by Django 4.0.2 on 2022-03-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topTen', '0010_alter_stock_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='news',
            field=models.TextField(blank=True, default='xxx'),
        ),
    ]
