# Generated by Django 4.0.2 on 2022-03-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_xxx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='xxx',
        ),
        migrations.AddField(
            model_name='mysector',
            name='stocks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='mysector',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
