# Generated by Django 4.0.2 on 2022-03-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_mysector_stocks_stock_xsectorx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ave',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
