# Generated by Django 4.0.2 on 2022-03-02 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_ave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='xsectorx',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocks.mysector', to_field='name'),
        ),
    ]
