# Generated by Django 4.0.2 on 2022-03-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_stock_averagevolume_stock_averagevolume10days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dividendRate',
            field=models.FloatField(default=0, null=True),
        ),
    ]
