# Generated by Django 4.0.2 on 2022-03-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_stock_forwardpe_alter_stock_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='news',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='revenuePerShare',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='totalCashPerShare',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='totalRevenue',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trailingAnnualDividendRate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trailingPE',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='twoHundredDayAverage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
