# Generated by Django 4.0.2 on 2022-03-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_alter_stock_news_alter_stock_revenuepershare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
