# Generated by Django 4.0.2 on 2022-03-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_stock_grossprofit_stock_pricetosalestrailing12months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='grossProfit',
        ),
        migrations.AlterField(
            model_name='stock',
            name='priceToSalesTrailing12Months',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
