# Generated by Django 4.0.2 on 2022-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_alter_stock_averagevolume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='myzero',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
    ]
