# Generated by Django 4.0.2 on 2022-03-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0024_stock_myzero'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='grossMargins',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='grossProfits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='profitMargins',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='targetPriceLow',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
