# Generated by Django 4.0.2 on 2022-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_stock_bookvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bookValue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
