# Generated by Django 4.0.2 on 2022-03-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_alter_stock_bookvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='forwardEPS',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='trailingEPS',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
