# Generated by Django 4.0.2 on 2022-03-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_stock_forwardeps_stock_trailingeps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='feps',
            new_name='PriceToBook',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fpe',
            new_name='returnOnEquity',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='ptb',
            new_name='totalAssets',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='roe',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='teps',
        ),
    ]
