# Generated by Django 4.0.2 on 2022-03-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_remove_stock_totalassets'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
