# Generated by Django 4.0.2 on 2022-03-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0031_stock_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
