# Generated by Django 4.0.2 on 2022-03-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0032_stock_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
